import type { GitHubProject } from '@/types/project'

export const mockProjects: GitHubProject[] = [
  {
    id: '1',
    name: 'react',
    fullName: 'facebook/react',
    description: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    stars: 218000,
    forks: 45000,
    watchers: 6700,
    openIssues: 580,
    topics: ['frontend', 'ui', 'javascript', 'library', 'react'],
    createdAt: '2013-05-24T16:15:36Z',
    updatedAt: '2024-01-15T10:30:00Z',
    homepage: 'https://react.dev',
    size: 8900,
    isPrivate: false,
    owner: {
      login: 'facebook',
      avatarUrl: 'https://github.com/facebook.png',
      type: 'Organization'
    },
    readme: '# React\n\nReact is a JavaScript library for building user interfaces.\n\n## Features\n\n- Declarative\n- Component-Based\n- Learn Once, Write Anywhere\n\n## Getting Started\n\n```bash\nnpx create-react-app my-app\ncd my-app\nnpm start\n```',
    license: 'MIT',
    defaultBranch: 'main'
  },
  {
    id: '2',
    name: 'vue',
    fullName: 'vuejs/core',
    description: 'Vue.js - The Progressive JavaScript Framework',
    language: 'TypeScript',
    languageColor: '#2b7489',
    stars: 45000,
    forks: 7800,
    watchers: 1200,
    openIssues: 320,
    topics: ['frontend', 'ui', 'typescript', 'framework', 'vue'],
    createdAt: '2014-02-25T15:30:00Z',
    updatedAt: '2024-01-14T14:20:00Z',
    homepage: 'https://vuejs.org',
    size: 5600,
    isPrivate: false,
    owner: {
      login: 'vuejs',
      avatarUrl: 'https://github.com/vuejs.png',
      type: 'Organization'
    },
    readme: '# Vue.js\n\nVue.js is a progressive JavaScript framework.\n\n## Features\n\n- Approachable\n- Performant\n- Versatile\n\n## Installation\n\n```bash\nnpm install vue\n```',
    license: 'MIT',
    defaultBranch: 'main'
  },
  {
    id: '3',
    name: 'tensorflow',
    fullName: 'tensorflow/tensorflow',
    description: 'An Open Source Machine Learning Framework for Everyone',
    language: 'C++',
    languageColor: '#f34b7d',
    stars: 182000,
    forks: 89000,
    watchers: 9800,
    openIssues: 2100,
    topics: ['machine-learning', 'ai', 'deep-learning', 'python', 'c++'],
    createdAt: '2015-11-09T02:20:00Z',
    updatedAt: '2024-01-13T09:45:00Z',
    homepage: 'https://www.tensorflow.org',
    size: 125000,
    isPrivate: false,
    owner: {
      login: 'tensorflow',
      avatarUrl: 'https://github.com/tensorflow.png',
      type: 'Organization'
    },
    readme: '# TensorFlow\n\nTensorFlow is an end-to-end open source platform for machine learning.\n\n## Features\n\n- Robust ML model\n- Flexible\n- Portable\n\n## Quick Start\n\n```python\nimport tensorflow as tf\n```',
    license: 'Apache-2.0',
    defaultBranch: 'master'
  },
  {
    id: '4',
    name: 'vscode',
    fullName: 'microsoft/vscode',
    description: 'Visual Studio Code',
    language: 'TypeScript',
    languageColor: '#2b7489',
    stars: 156000,
    forks: 27000,
    watchers: 5600,
    openIssues: 8900,
    topics: ['editor', 'ide', 'typescript', 'development-tools', 'vscode'],
    createdAt: '2015-04-14T16:30:00Z',
    updatedAt: '2024-01-16T08:15:00Z',
    homepage: 'https://code.visualstudio.com',
    size: 45000,
    isPrivate: false,
    owner: {
      login: 'microsoft',
      avatarUrl: 'https://github.com/microsoft.png',
      type: 'Organization'
    },
    readme: '# Visual Studio Code\n\nVisual Studio Code is a lightweight but powerful source code editor.\n\n## Features\n\n- IntelliSense\n- Debugging\n- Git Integration\n\n## Download\n\nVisit https://code.visualstudio.com',
    license: 'MIT',
    defaultBranch: 'main'
  },
  {
    id: '5',
    name: 'linux',
    fullName: 'torvalds/linux',
    description: 'Linux kernel source tree',
    language: 'C',
    languageColor: '#555555',
    stars: 168000,
    forks: 54000,
    watchers: 8900,
    openIssues: 1200,
    topics: ['kernel', 'operating-system', 'c', 'linux', 'system'],
    createdAt: '2011-09-04T01:41:52Z',
    updatedAt: '2024-01-16T11:30:00Z',
    size: 890000,
    isPrivate: false,
    owner: {
      login: 'torvalds',
      avatarUrl: 'https://github.com/torvalds.png',
      type: 'User'
    },
    readme: '# Linux Kernel\n\nLinux is a Unix-like computer operating system.\n\n## Building\n\n```bash\nmake defconfig\nmake\n```',
    license: 'GPL-2.0',
    defaultBranch: 'master'
  },
  {
    id: '6',
    name: 'django',
    fullName: 'django/django',
    description: 'The Web framework for perfectionists with deadlines.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 78000,
    forks: 31000,
    watchers: 3200,
    openIssues: 2300,
    topics: ['web', 'framework', 'python', 'backend', 'django'],
    createdAt: '2005-07-21T00:00:00Z',
    updatedAt: '2024-01-15T16:45:00Z',
    homepage: 'https://www.djangoproject.com',
    size: 23000,
    isPrivate: false,
    owner: {
      login: 'django',
      avatarUrl: 'https://github.com/django.png',
      type: 'Organization'
    },
    readme: '# Django\n\nDjango is a high-level Python web framework.\n\n## Features\n\n- Rapid development\n- Clean design\n- Batteries included\n\n## Installation\n\n```bash\npip install django\n```',
    license: 'BSD-3-Clause',
    defaultBranch: 'main'
  },
  {
    id: '7',
    name: 'go',
    fullName: 'golang/go',
    description: 'The Go programming language',
    language: 'Go',
    languageColor: '#00ADD8',
    stars: 118000,
    forks: 17000,
    watchers: 4500,
    openIssues: 890,
    topics: ['programming-language', 'go', 'golang', 'compiler', 'system'],
    createdAt: '2009-11-10T00:00:00Z',
    updatedAt: '2024-01-16T07:20:00Z',
    homepage: 'https://go.dev',
    size: 67000,
    isPrivate: false,
    owner: {
      login: 'golang',
      avatarUrl: 'https://github.com/golang.png',
      type: 'Organization'
    },
    readme: '# The Go Programming Language\n\nGo is an open source programming language.\n\n## Features\n\n- Simple\n- Fast\n- Safe\n\n## Installation\n\nVisit https://go.dev/dl/',
    license: 'BSD-3-Clause',
    defaultBranch: 'master'
  },
  {
    id: '8',
    name: 'rust',
    fullName: 'rust-lang/rust',
    description: 'Empowering everyone to build reliable and efficient software.',
    language: 'Rust',
    languageColor: '#dea584',
    stars: 92000,
    forks: 12000,
    watchers: 2800,
    openIssues: 7800,
    topics: ['programming-language', 'rust', 'compiler', 'system', 'memory-safety'],
    createdAt: '2010-01-26T00:00:00Z',
    updatedAt: '2024-01-16T09:10:00Z',
    homepage: 'https://www.rust-lang.org',
    size: 78000,
    isPrivate: false,
    owner: {
      login: 'rust-lang',
      avatarUrl: 'https://github.com/rust-lang.png',
      type: 'Organization'
    },
    readme: '# Rust\n\nRust is a programming language empowering everyone to build reliable and efficient software.\n\n## Features\n\n- Memory safety\n- Concurrency\n- Performance\n\n## Installation\n\nVisit https://rustup.rs/',
    license: 'MIT OR Apache-2.0',
    defaultBranch: 'master'
  },
  {
    id: '9',
    name: 'node',
    fullName: 'nodejs/node',
    description: 'Node.js JavaScript runtime',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    stars: 102000,
    forks: 28000,
    watchers: 3400,
    openIssues: 890,
    topics: ['javascript', 'runtime', 'nodejs', 'backend', 'server'],
    createdAt: '2009-11-10T00:00:00Z',
    updatedAt: '2024-01-15T13:25:00Z',
    homepage: 'https://nodejs.org',
    size: 56000,
    isPrivate: false,
    owner: {
      login: 'nodejs',
      avatarUrl: 'https://github.com/nodejs.png',
      type: 'Organization'
    },
    readme: '# Node.js\n\nNode.js is a JavaScript runtime built on Chrome\'s V8 JavaScript engine.\n\n## Features\n\n- Asynchronous I/O\n- Event-driven\n- Cross-platform\n\n## Installation\n\nVisit https://nodejs.org/',
    license: 'MIT',
    defaultBranch: 'main'
  },
  {
    id: '10',
    name: 'nextjs',
    fullName: 'vercel/next.js',
    description: 'The React Framework for the Web',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    stars: 123000,
    forks: 25000,
    watchers: 2900,
    openIssues: 3400,
    topics: ['frontend', 'react', 'framework', 'ssr', 'nextjs'],
    createdAt: '2016-10-25T00:00:00Z',
    updatedAt: '2024-01-16T12:00:00Z',
    homepage: 'https://nextjs.org',
    size: 34000,
    isPrivate: false,
    owner: {
      login: 'vercel',
      avatarUrl: 'https://github.com/vercel.png',
      type: 'Organization'
    },
    readme: '# Next.js\n\nNext.js is a React framework for the web.\n\n## Features\n\n- Server-side rendering\n- Static site generation\n- API routes\n\n## Getting Started\n\n```bash\nnpx create-next-app@latest\n```',
    license: 'MIT',
    defaultBranch: 'canary'
  },
  {
    id: '11',
    name: 'typescript',
    fullName: 'microsoft/TypeScript',
    description: 'TypeScript is a superset of JavaScript that compiles to clean JavaScript output.',
    language: 'TypeScript',
    languageColor: '#2b7489',
    stars: 98000,
    forks: 12000,
    watchers: 2300,
    openIssues: 5600,
    topics: ['typescript', 'javascript', 'programming-language', 'compiler', 'microsoft'],
    createdAt: '2012-10-01T00:00:00Z',
    updatedAt: '2024-01-15T14:40:00Z',
    homepage: 'https://www.typescriptlang.org',
    size: 45000,
    isPrivate: false,
    owner: {
      login: 'microsoft',
      avatarUrl: 'https://github.com/microsoft.png',
      type: 'Organization'
    },
    readme: '# TypeScript\n\nTypeScript is a superset of JavaScript.\n\n## Features\n\n- Type safety\n- Tooling\n- Modern JavaScript\n\n## Installation\n\n```bash\nnpm install -g typescript\n```',
    license: 'Apache-2.0',
    defaultBranch: 'main'
  },
  {
    id: '12',
    name: 'kubernetes',
    fullName: 'kubernetes/kubernetes',
    description: 'Production-Grade Container Orchestration',
    language: 'Go',
    languageColor: '#00ADD8',
    stars: 106000,
    forks: 38000,
    watchers: 5600,
    openIssues: 4500,
    topics: ['container', 'orchestration', 'kubernetes', 'go', 'devops'],
    createdAt: '2014-06-06T00:00:00Z',
    updatedAt: '2024-01-16T10:50:00Z',
    homepage: 'https://kubernetes.io',
    size: 89000,
    isPrivate: false,
    owner: {
      login: 'kubernetes',
      avatarUrl: 'https://github.com/kubernetes.png',
      type: 'Organization'
    },
    readme: '# Kubernetes\n\nKubernetes is an open-source system for automating deployment, scaling, and management of containerized applications.\n\n## Features\n\n- Automated rollouts and rollbacks\n- Service discovery and load balancing\n- Storage orchestration\n\n## Getting Started\n\nVisit https://kubernetes.io/docs/',
    license: 'Apache-2.0',
    defaultBranch: 'master'
  },
  {
    id: '13',
    name: 'docker',
    fullName: 'docker/docker-ce',
    description: 'Docker - the open-source application container engine',
    language: 'Go',
    languageColor: '#00ADD8',
    stars: 68000,
    forks: 19000,
    watchers: 3200,
    openIssues: 1200,
    topics: ['container', 'docker', 'virtualization', 'devops', 'infrastructure'],
    createdAt: '2013-01-30T00:00:00Z',
    updatedAt: '2024-01-15T15:30:00Z',
    homepage: 'https://www.docker.com',
    size: 23000,
    isPrivate: false,
    owner: {
      login: 'docker',
      avatarUrl: 'https://github.com/docker.png',
      type: 'Organization'
    },
    readme: '# Docker\n\nDocker is an open platform for developing, shipping, and running applications.\n\n## Features\n\n- Containerization\n- Portability\n- Isolation\n\n## Installation\n\nVisit https://docs.docker.com/get-docker/',
    license: 'Apache-2.0',
    defaultBranch: 'master'
  },
  {
    id: '14',
    name: 'electron',
    fullName: 'electron/electron',
    description: 'Build cross-platform desktop apps with JavaScript, HTML, and CSS',
    language: 'C++',
    languageColor: '#f34b7d',
    stars: 108000,
    forks: 14000,
    watchers: 2100,
    openIssues: 3400,
    topics: ['desktop', 'electron', 'javascript', 'cross-platform', 'gui'],
    createdAt: '2013-04-11T00:00:00Z',
    updatedAt: '2024-01-16T08:45:00Z',
    homepage: 'https://www.electronjs.org',
    size: 67000,
    isPrivate: false,
    owner: {
      login: 'electron',
      avatarUrl: 'https://github.com/electron.png',
      type: 'Organization'
    },
    readme: '# Electron\n\nElectron is a framework for creating native applications with web technologies.\n\n## Features\n\n- Cross-platform\n- Web technologies\n- Native APIs\n\n## Quick Start\n\n```bash\nnpm install electron\n```',
    license: 'MIT',
    defaultBranch: 'main'
  },
  {
    id: '15',
    name: 'tailwindcss',
    fullName: 'tailwindlabs/tailwindcss',
    description: 'A utility-first CSS framework for rapid UI development.',
    language: 'TypeScript',
    languageColor: '#2b7489',
    stars: 78000,
    forks: 4000,
    watchers: 890,
    openIssues: 560,
    topics: ['css', 'framework', 'tailwindcss', 'frontend', 'ui'],
    createdAt: '2017-10-17T00:00:00Z',
    updatedAt: '2024-01-16T11:20:00Z',
    homepage: 'https://tailwindcss.com',
    size: 12000,
    isPrivate: false,
    owner: {
      login: 'tailwindlabs',
      avatarUrl: 'https://github.com/tailwindlabs.png',
      type: 'Organization'
    },
    readme: '# Tailwind CSS\n\nTailwind CSS is a utility-first CSS framework.\n\n## Features\n\n- Utility-first\n- Responsive\n- Customizable\n\n## Installation\n\n```bash\nnpm install -D tailwindcss\n```',
    license: 'MIT',
    defaultBranch: 'next'
  },
  {
    id: '16',
    name: 'pytorch',
    fullName: 'pytorch/pytorch',
    description: 'Tensors and Dynamic neural networks in Python with strong GPU acceleration',
    language: 'C++',
    languageColor: '#f34b7d',
    stars: 74000,
    forks: 20000,
    watchers: 2100,
    openIssues: 5600,
    topics: ['machine-learning', 'deep-learning', 'python', 'ai', 'pytorch'],
    createdAt: '2016-08-26T00:00:00Z',
    updatedAt: '2024-01-15T17:10:00Z',
    homepage: 'https://pytorch.org',
    size: 89000,
    isPrivate: false,
    owner: {
      login: 'pytorch',
      avatarUrl: 'https://github.com/pytorch.png',
      type: 'Organization'
    },
    readme: '# PyTorch\n\nPyTorch is an open source machine learning library.\n\n## Features\n\n- Tensor computation\n- Dynamic neural networks\n- GPU acceleration\n\n## Installation\n\n```bash\npip install torch\n```',
    license: 'BSD-3-Clause',
    defaultBranch: 'master'
  },
  {
    id: '17',
    name: 'redis',
    fullName: 'redis/redis',
    description: 'Redis is an in-memory database that persists on disk.',
    language: 'C',
    languageColor: '#555555',
    stars: 64000,
    forks: 23000,
    watchers: 3400,
    openIssues: 2300,
    topics: ['database', 'redis', 'cache', 'key-value', 'storage'],
    createdAt: '2009-03-26T00:00:00Z',
    updatedAt: '2024-01-16T06:30:00Z',
    homepage: 'https://redis.io',
    size: 34000,
    isPrivate: false,
    owner: {
      login: 'redis',
      avatarUrl: 'https://github.com/redis.png',
      type: 'Organization'
    },
    readme: '# Redis\n\nRedis is an open source, in-memory data structure store.\n\n## Features\n\n- In-memory\n- Persistence\n- Data structures\n\n## Installation\n\nVisit https://redis.io/download',
    license: 'BSD-3-Clause',
    defaultBranch: 'unstable'
  },
  {
    id: '18',
    name: 'vite',
    fullName: 'vitejs/vite',
    description: 'Next generation frontend tooling. It\'s fast!',
    language: 'TypeScript',
    languageColor: '#2b7489',
    stars: 64000,
    forks: 5600,
    watchers: 890,
    openIssues: 890,
    topics: ['build-tool', 'vite', 'frontend', 'devtools', 'bundler'],
    createdAt: '2020-04-13T00:00:00Z',
    updatedAt: '2024-01-16T13:00:00Z',
    homepage: 'https://vitejs.dev',
    size: 8900,
    isPrivate: false,
    owner: {
      login: 'vitejs',
      avatarUrl: 'https://github.com/vitejs.png',
      type: 'Organization'
    },
    readme: '# Vite\n\nVite is a build tool that aims to provide a faster and leaner development experience.\n\n## Features\n\n- Instant server start\n- Lightning fast HMR\n- Rich features\n\n## Getting Started\n\n```bash\nnpm create vite@latest\n```',
    license: 'MIT',
    defaultBranch: 'main'
  },
  {
    id: '19',
    name: 'graphql',
    fullName: 'graphql/graphql-js',
    description: 'A reference implementation of GraphQL for JavaScript',
    language: 'TypeScript',
    languageColor: '#2b7489',
    stars: 19000,
    forks: 2300,
    watchers: 560,
    openIssues: 450,
    topics: ['graphql', 'api', 'query-language', 'javascript', 'typescript'],
    createdAt: '2015-07-08T00:00:00Z',
    updatedAt: '2024-01-15T18:20:00Z',
    homepage: 'https://graphql.org',
    size: 12000,
    isPrivate: false,
    owner: {
      login: 'graphql',
      avatarUrl: 'https://github.com/graphql.png',
      type: 'Organization'
    },
    readme: '# GraphQL\n\nGraphQL is a query language for APIs.\n\n## Features\n\n- Query language\n- Type system\n- Introspection\n\n## Installation\n\n```bash\nnpm install graphql\n```',
    license: 'MIT',
    defaultBranch: 'main'
  },
  {
    id: '20',
    name: 'nestjs',
    fullName: 'nestjs/nest',
    description: 'A progressive Node.js framework for building efficient, scalable enterprise-grade server-side applications.',
    language: 'TypeScript',
    languageColor: '#2b7489',
    stars: 64000,
    forks: 7200,
    watchers: 890,
    openIssues: 340,
    topics: ['nodejs', 'framework', 'typescript', 'backend', 'nestjs'],
    createdAt: '2017-01-01T00:00:00Z',
    updatedAt: '2024-01-16T09:30:00Z',
    homepage: 'https://nestjs.com',
    size: 23000,
    isPrivate: false,
    owner: {
      login: 'nestjs',
      avatarUrl: 'https://github.com/nestjs.png',
      type: 'Organization'
    },
    readme: '# NestJS\n\nNestJS is a framework for building efficient Node.js server-side applications.\n\n## Features\n\n- TypeScript\n- Modular\n- Dependency injection\n\n## Installation\n\n```bash\nnpm i @nestjs/core\n```',
    license: 'MIT',
    defaultBranch: 'master'
  }
]

export const loadMockProjects = (): GitHubProject[] => {
  return mockProjects
}
